import torch

model = torch.load('assets/weights/charlene_blanchette.pth')

weights = model['weight']

new_weights = {}

conversion_weight_labels = {
'enc_p.encoder.attn_layers.0.emb_rel_k':     'enc_p.encoder.layers.0.att.emb_rel_k',
'enc_p.encoder.attn_layers.0.emb_rel_v':     'enc_p.encoder.layers.0.att.emb_rel_v',
'enc_p.encoder.attn_layers.0.conv_q.weight': 'enc_p.encoder.layers.0.att.conv_q.weight',
'enc_p.encoder.attn_layers.0.conv_q.bias':   'enc_p.encoder.layers.0.att.conv_q.bias',
'enc_p.encoder.attn_layers.0.conv_k.weight': 'enc_p.encoder.layers.0.att.conv_k.weight',
'enc_p.encoder.attn_layers.0.conv_k.bias':   'enc_p.encoder.layers.0.att.conv_k.bias',
'enc_p.encoder.attn_layers.0.conv_v.weight': 'enc_p.encoder.layers.0.att.conv_v.weight',
'enc_p.encoder.attn_layers.0.conv_v.bias':   'enc_p.encoder.layers.0.att.conv_v.bias',
'enc_p.encoder.attn_layers.0.conv_o.weight': 'enc_p.encoder.layers.0.att.conv_o.weight',
'enc_p.encoder.attn_layers.0.conv_o.bias':   'enc_p.encoder.layers.0.att.conv_o.bias',

'enc_p.encoder.attn_layers.1.emb_rel_k':     'enc_p.encoder.layers.1.att.emb_rel_k',
'enc_p.encoder.attn_layers.1.emb_rel_v':     'enc_p.encoder.layers.1.att.emb_rel_v',
'enc_p.encoder.attn_layers.1.conv_q.weight': 'enc_p.encoder.layers.1.att.conv_q.weight',
'enc_p.encoder.attn_layers.1.conv_q.bias':   'enc_p.encoder.layers.1.att.conv_q.bias',
'enc_p.encoder.attn_layers.1.conv_k.weight': 'enc_p.encoder.layers.1.att.conv_k.weight',
'enc_p.encoder.attn_layers.1.conv_k.bias':   'enc_p.encoder.layers.1.att.conv_k.bias',
'enc_p.encoder.attn_layers.1.conv_v.weight': 'enc_p.encoder.layers.1.att.conv_v.weight',
'enc_p.encoder.attn_layers.1.conv_v.bias':   'enc_p.encoder.layers.1.att.conv_v.bias',
'enc_p.encoder.attn_layers.1.conv_o.weight': 'enc_p.encoder.layers.1.att.conv_o.weight',
'enc_p.encoder.attn_layers.1.conv_o.bias':   'enc_p.encoder.layers.1.att.conv_o.bias',

'enc_p.encoder.attn_layers.2.emb_rel_k':     'enc_p.encoder.layers.2.att.emb_rel_k',
'enc_p.encoder.attn_layers.2.emb_rel_v':     'enc_p.encoder.layers.2.att.emb_rel_v',
'enc_p.encoder.attn_layers.2.conv_q.weight': 'enc_p.encoder.layers.2.att.conv_q.weight',
'enc_p.encoder.attn_layers.2.conv_q.bias':   'enc_p.encoder.layers.2.att.conv_q.bias',
'enc_p.encoder.attn_layers.2.conv_k.weight': 'enc_p.encoder.layers.2.att.conv_k.weight',
'enc_p.encoder.attn_layers.2.conv_k.bias':   'enc_p.encoder.layers.2.att.conv_k.bias',
'enc_p.encoder.attn_layers.2.conv_v.weight': 'enc_p.encoder.layers.2.att.conv_v.weight',
'enc_p.encoder.attn_layers.2.conv_v.bias':   'enc_p.encoder.layers.2.att.conv_v.bias',
'enc_p.encoder.attn_layers.2.conv_o.weight': 'enc_p.encoder.layers.2.att.conv_o.weight',
'enc_p.encoder.attn_layers.2.conv_o.bias':   'enc_p.encoder.layers.2.att.conv_o.bias',

'enc_p.encoder.attn_layers.3.emb_rel_k':     'enc_p.encoder.layers.3.att.emb_rel_k',
'enc_p.encoder.attn_layers.3.emb_rel_v':     'enc_p.encoder.layers.3.att.emb_rel_v',
'enc_p.encoder.attn_layers.3.conv_q.weight': 'enc_p.encoder.layers.3.att.conv_q.weight',
'enc_p.encoder.attn_layers.3.conv_q.bias':   'enc_p.encoder.layers.3.att.conv_q.bias',
'enc_p.encoder.attn_layers.3.conv_k.weight': 'enc_p.encoder.layers.3.att.conv_k.weight',
'enc_p.encoder.attn_layers.3.conv_k.bias':   'enc_p.encoder.layers.3.att.conv_k.bias',
'enc_p.encoder.attn_layers.3.conv_v.weight': 'enc_p.encoder.layers.3.att.conv_v.weight',
'enc_p.encoder.attn_layers.3.conv_v.bias':   'enc_p.encoder.layers.3.att.conv_v.bias',
'enc_p.encoder.attn_layers.3.conv_o.weight': 'enc_p.encoder.layers.3.att.conv_o.weight',
'enc_p.encoder.attn_layers.3.conv_o.bias':   'enc_p.encoder.layers.3.att.conv_o.bias',

'enc_p.encoder.attn_layers.4.emb_rel_k':     'enc_p.encoder.layers.4.att.emb_rel_k',
'enc_p.encoder.attn_layers.4.emb_rel_v':     'enc_p.encoder.layers.4.att.emb_rel_v',
'enc_p.encoder.attn_layers.4.conv_q.weight': 'enc_p.encoder.layers.4.att.conv_q.weight',
'enc_p.encoder.attn_layers.4.conv_q.bias':   'enc_p.encoder.layers.4.att.conv_q.bias',
'enc_p.encoder.attn_layers.4.conv_k.weight': 'enc_p.encoder.layers.4.att.conv_k.weight',
'enc_p.encoder.attn_layers.4.conv_k.bias':   'enc_p.encoder.layers.4.att.conv_k.bias',
'enc_p.encoder.attn_layers.4.conv_v.weight': 'enc_p.encoder.layers.4.att.conv_v.weight',
'enc_p.encoder.attn_layers.4.conv_v.bias':   'enc_p.encoder.layers.4.att.conv_v.bias',
'enc_p.encoder.attn_layers.4.conv_o.weight': 'enc_p.encoder.layers.4.att.conv_o.weight',
'enc_p.encoder.attn_layers.4.conv_o.bias':   'enc_p.encoder.layers.4.att.conv_o.bias',

'enc_p.encoder.attn_layers.2.emb_rel_k':     'enc_p.encoder.layers.5.att.emb_rel_k',
'enc_p.encoder.attn_layers.2.emb_rel_v':     'enc_p.encoder.layers.5.att.emb_rel_v',
'enc_p.encoder.attn_layers.2.conv_q.weight': 'enc_p.encoder.layers.5.att.conv_q.weight',
'enc_p.encoder.attn_layers.2.conv_q.bias':   'enc_p.encoder.layers.5.att.conv_q.bias',
'enc_p.encoder.attn_layers.2.conv_k.weight': 'enc_p.encoder.layers.5.att.conv_k.weight',
'enc_p.encoder.attn_layers.2.conv_k.bias':   'enc_p.encoder.layers.5.att.conv_k.bias',
'enc_p.encoder.attn_layers.2.conv_v.weight': 'enc_p.encoder.layers.5.att.conv_v.weight',
'enc_p.encoder.attn_layers.2.conv_v.bias':   'enc_p.encoder.layers.5.att.conv_v.bias',
'enc_p.encoder.attn_layers.2.conv_o.weight': 'enc_p.encoder.layers.5.att.conv_o.weight',
'enc_p.encoder.attn_layers.2.conv_o.bias':   'enc_p.encoder.layers.5.att.conv_o.bias',

'enc_p.encoder.norm_layers_1.0.gamma' : 'enc_p.encoder.layers.0.norm_1.gamma',
'enc_p.encoder.norm_layers_1.0.beta' :  'enc_p.encoder.layers.0.norm_1.beta',
'enc_p.encoder.norm_layers_1.1.gamma' : 'enc_p.encoder.layers.1.norm_1.gamma',
'enc_p.encoder.norm_layers_1.1.beta' :  'enc_p.encoder.layers.1.norm_1.beta',
'enc_p.encoder.norm_layers_1.2.gamma' : 'enc_p.encoder.layers.2.norm_1.gamma',
'enc_p.encoder.norm_layers_1.2.beta' :  'enc_p.encoder.layers.2.norm_1.beta',
'enc_p.encoder.norm_layers_1.3.gamma' : 'enc_p.encoder.layers.3.norm_1.gamma',
'enc_p.encoder.norm_layers_1.3.beta' :  'enc_p.encoder.layers.3.norm_1.beta',
'enc_p.encoder.norm_layers_1.4.gamma' : 'enc_p.encoder.layers.4.norm_1.gamma',
'enc_p.encoder.norm_layers_1.4.beta' :  'enc_p.encoder.layers.4.norm_1.beta',
'enc_p.encoder.norm_layers_1.5.gamma' : 'enc_p.encoder.layers.5.norm_1.gamma',
'enc_p.encoder.norm_layers_1.5.beta' :  'enc_p.encoder.layers.5.norm_1.beta',

'enc_p.encoder.norm_layers_2.0.gamma' : 'enc_p.encoder.layers.0.norm_2.gamma',
'enc_p.encoder.norm_layers_2.0.beta' :  'enc_p.encoder.layers.0.norm_2.beta',
'enc_p.encoder.norm_layers_2.1.gamma' : 'enc_p.encoder.layers.1.norm_2.gamma',
'enc_p.encoder.norm_layers_2.1.beta' :  'enc_p.encoder.layers.1.norm_2.beta',
'enc_p.encoder.norm_layers_2.2.gamma' : 'enc_p.encoder.layers.2.norm_2.gamma',
'enc_p.encoder.norm_layers_2.2.beta' :  'enc_p.encoder.layers.2.norm_2.beta',
'enc_p.encoder.norm_layers_2.3.gamma' : 'enc_p.encoder.layers.3.norm_2.gamma',
'enc_p.encoder.norm_layers_2.3.beta' :  'enc_p.encoder.layers.3.norm_2.beta',
'enc_p.encoder.norm_layers_2.4.gamma' : 'enc_p.encoder.layers.4.norm_2.gamma',
'enc_p.encoder.norm_layers_2.4.beta' :  'enc_p.encoder.layers.4.norm_2.beta',
'enc_p.encoder.norm_layers_2.5.gamma' : 'enc_p.encoder.layers.5.norm_2.gamma',
'enc_p.encoder.norm_layers_2.5.beta' :  'enc_p.encoder.layers.5.norm_2.beta',

'enc_p.encoder.ffn_layers.0.conv_1.weight' : 'enc_p.encoder.layers.0.ffn.conv_1.weight',
'enc_p.encoder.ffn_layers.0.conv_1.bias':    'enc_p.encoder.layers.0.ffn.conv_1.bias',
'enc_p.encoder.ffn_layers.0.conv_2.weight':  'enc_p.encoder.layers.0.ffn.conv_2.weight',
'enc_p.encoder.ffn_layers.0.conv_2.bias':    'enc_p.encoder.layers.0.ffn.conv_2.bias',

'enc_p.encoder.ffn_layers.1.conv_1.weight' : 'enc_p.encoder.layers.1.ffn.conv_1.weight',
'enc_p.encoder.ffn_layers.1.conv_1.bias':    'enc_p.encoder.layers.1.ffn.conv_1.bias',
'enc_p.encoder.ffn_layers.1.conv_2.weight':  'enc_p.encoder.layers.1.ffn.conv_2.weight',
'enc_p.encoder.ffn_layers.1.conv_2.bias':    'enc_p.encoder.layers.1.ffn.conv_2.bias',

'enc_p.encoder.ffn_layers.2.conv_1.weight' : 'enc_p.encoder.layers.2.ffn.conv_1.weight',
'enc_p.encoder.ffn_layers.2.conv_1.bias':    'enc_p.encoder.layers.2.ffn.conv_1.bias',
'enc_p.encoder.ffn_layers.2.conv_2.weight':  'enc_p.encoder.layers.2.ffn.conv_2.weight',
'enc_p.encoder.ffn_layers.2.conv_2.bias':    'enc_p.encoder.layers.2.ffn.conv_2.bias',

'enc_p.encoder.ffn_layers.3.conv_1.weight' : 'enc_p.encoder.layers.3.ffn.conv_1.weight',
'enc_p.encoder.ffn_layers.3.conv_1.bias':    'enc_p.encoder.layers.3.ffn.conv_1.bias',
'enc_p.encoder.ffn_layers.3.conv_2.weight':  'enc_p.encoder.layers.3.ffn.conv_2.weight',
'enc_p.encoder.ffn_layers.3.conv_2.bias':    'enc_p.encoder.layers.3.ffn.conv_2.bias',

'enc_p.encoder.ffn_layers.4.conv_1.weight' : 'enc_p.encoder.layers.4.ffn.conv_1.weight',
'enc_p.encoder.ffn_layers.4.conv_1.bias':    'enc_p.encoder.layers.4.ffn.conv_1.bias',
'enc_p.encoder.ffn_layers.4.conv_2.weight':  'enc_p.encoder.layers.4.ffn.conv_2.weight',
'enc_p.encoder.ffn_layers.4.conv_2.bias':    'enc_p.encoder.layers.4.ffn.conv_2.bias',

'enc_p.encoder.ffn_layers.5.conv_1.weight' : 'enc_p.encoder.layers.5.ffn.conv_1.weight',
'enc_p.encoder.ffn_layers.5.conv_1.bias':    'enc_p.encoder.layers.5.ffn.conv_1.bias',
'enc_p.encoder.ffn_layers.5.conv_2.weight':  'enc_p.encoder.layers.5.ffn.conv_2.weight',
'enc_p.encoder.ffn_layers.5.conv_2.bias':    'enc_p.encoder.layers.5.ffn.conv_2.bias',

'dec.noise_convs.0.weight': 'dec.layers.0.noise_convs.weight',
'dec.noise_convs.0.bias':   'dec.layers.0.noise_convs.bias',
'dec.noise_convs.1.weight': 'dec.layers.1.noise_convs.weight',
'dec.noise_convs.1.bias':   'dec.layers.1.noise_convs.bias',
'dec.noise_convs.2.weight': 'dec.layers.2.noise_convs.weight',
'dec.noise_convs.2.bias':   'dec.layers.2.noise_convs.bias',
'dec.noise_convs.3.weight': 'dec.layers.3.noise_convs.weight',
'dec.noise_convs.3.bias':   'dec.layers.3.noise_convs.bias',

'dec.ups.0.bias':     'dec.layers.0.ups.bias',
'dec.ups.0.weight_g': 'dec.layers.0.ups.weight_g',
'dec.ups.0.weight_v': 'dec.layers.0.ups.weight_v',
'dec.ups.1.bias':     'dec.layers.1.ups.bias',
'dec.ups.1.weight_g': 'dec.layers.1.ups.weight_g',
'dec.ups.1.weight_v': 'dec.layers.1.ups.weight_v',
'dec.ups.2.bias':     'dec.layers.2.ups.bias',
'dec.ups.2.weight_g': 'dec.layers.2.ups.weight_g',
'dec.ups.2.weight_v': 'dec.layers.2.ups.weight_v',
'dec.ups.3.bias':     'dec.layers.3.ups.bias',
'dec.ups.3.weight_g': 'dec.layers.3.ups.weight_g',
'dec.ups.3.weight_v': 'dec.layers.3.ups.weight_v',

'dec.resblocks.0.convs1.0.bias':     'dec.layers.0.resblocks.0.convs1.0.bias',
'dec.resblocks.0.convs1.0.weight_g': 'dec.layers.0.resblocks.0.convs1.0.weight_g',
'dec.resblocks.0.convs1.0.weight_v': 'dec.layers.0.resblocks.0.convs1.0.weight_v',
'dec.resblocks.0.convs1.1.bias':     'dec.layers.0.resblocks.0.convs1.1.bias',
'dec.resblocks.0.convs1.1.weight_g': 'dec.layers.0.resblocks.0.convs1.1.weight_g',
'dec.resblocks.0.convs1.1.weight_v': 'dec.layers.0.resblocks.0.convs1.1.weight_v',
'dec.resblocks.0.convs1.2.bias':     'dec.layers.0.resblocks.0.convs1.2.bias',
'dec.resblocks.0.convs1.2.weight_g': 'dec.layers.0.resblocks.0.convs1.2.weight_g',
'dec.resblocks.0.convs1.2.weight_v': 'dec.layers.0.resblocks.0.convs1.2.weight_v',
'dec.resblocks.0.convs2.0.bias':     'dec.layers.0.resblocks.0.convs2.0.bias',
'dec.resblocks.0.convs2.0.weight_g': 'dec.layers.0.resblocks.0.convs2.0.weight_g',
'dec.resblocks.0.convs2.0.weight_v': 'dec.layers.0.resblocks.0.convs2.0.weight_v',
'dec.resblocks.0.convs2.1.bias':     'dec.layers.0.resblocks.0.convs2.1.bias',
'dec.resblocks.0.convs2.1.weight_g': 'dec.layers.0.resblocks.0.convs2.1.weight_g',
'dec.resblocks.0.convs2.1.weight_v': 'dec.layers.0.resblocks.0.convs2.1.weight_v',
'dec.resblocks.0.convs2.2.bias':     'dec.layers.0.resblocks.0.convs2.2.bias',
'dec.resblocks.0.convs2.2.weight_g': 'dec.layers.0.resblocks.0.convs2.2.weight_g',
'dec.resblocks.0.convs2.2.weight_v': 'dec.layers.0.resblocks.0.convs2.2.weight_v',

'dec.resblocks.1.convs1.0.bias':     'dec.layers.0.resblocks.1.convs1.0.bias',
'dec.resblocks.1.convs1.0.weight_g': 'dec.layers.0.resblocks.1.convs1.0.weight_g',
'dec.resblocks.1.convs1.0.weight_v': 'dec.layers.0.resblocks.1.convs1.0.weight_v',
'dec.resblocks.1.convs1.1.bias':     'dec.layers.0.resblocks.1.convs1.1.bias',
'dec.resblocks.1.convs1.1.weight_g': 'dec.layers.0.resblocks.1.convs1.1.weight_g',
'dec.resblocks.1.convs1.1.weight_v': 'dec.layers.0.resblocks.1.convs1.1.weight_v',
'dec.resblocks.1.convs1.2.bias':     'dec.layers.0.resblocks.1.convs1.2.bias',
'dec.resblocks.1.convs1.2.weight_g': 'dec.layers.0.resblocks.1.convs1.2.weight_g',
'dec.resblocks.1.convs1.2.weight_v': 'dec.layers.0.resblocks.1.convs1.2.weight_v',
'dec.resblocks.1.convs2.0.bias':     'dec.layers.0.resblocks.1.convs2.0.bias',
'dec.resblocks.1.convs2.0.weight_g': 'dec.layers.0.resblocks.1.convs2.0.weight_g',
'dec.resblocks.1.convs2.0.weight_v': 'dec.layers.0.resblocks.1.convs2.0.weight_v',
'dec.resblocks.1.convs2.1.bias':     'dec.layers.0.resblocks.1.convs2.1.bias',
'dec.resblocks.1.convs2.1.weight_g': 'dec.layers.0.resblocks.1.convs2.1.weight_g',
'dec.resblocks.1.convs2.1.weight_v': 'dec.layers.0.resblocks.1.convs2.1.weight_v',
'dec.resblocks.1.convs2.2.bias':     'dec.layers.0.resblocks.1.convs2.2.bias',
'dec.resblocks.1.convs2.2.weight_g': 'dec.layers.0.resblocks.1.convs2.2.weight_g',
'dec.resblocks.1.convs2.2.weight_v': 'dec.layers.0.resblocks.1.convs2.2.weight_v',

'dec.resblocks.2.convs1.0.bias':     'dec.layers.0.resblocks.2.convs1.0.bias',
'dec.resblocks.2.convs1.0.weight_g': 'dec.layers.0.resblocks.2.convs1.0.weight_g',
'dec.resblocks.2.convs1.0.weight_v': 'dec.layers.0.resblocks.2.convs1.0.weight_v',
'dec.resblocks.2.convs1.1.bias':     'dec.layers.0.resblocks.2.convs1.1.bias',
'dec.resblocks.2.convs1.1.weight_g': 'dec.layers.0.resblocks.2.convs1.1.weight_g',
'dec.resblocks.2.convs1.1.weight_v': 'dec.layers.0.resblocks.2.convs1.1.weight_v',
'dec.resblocks.2.convs1.2.bias':     'dec.layers.0.resblocks.2.convs1.2.bias',
'dec.resblocks.2.convs1.2.weight_g': 'dec.layers.0.resblocks.2.convs1.2.weight_g',
'dec.resblocks.2.convs1.2.weight_v': 'dec.layers.0.resblocks.2.convs1.2.weight_v',
'dec.resblocks.2.convs2.0.bias':     'dec.layers.0.resblocks.2.convs2.0.bias',
'dec.resblocks.2.convs2.0.weight_g': 'dec.layers.0.resblocks.2.convs2.0.weight_g',
'dec.resblocks.2.convs2.0.weight_v': 'dec.layers.0.resblocks.2.convs2.0.weight_v',
'dec.resblocks.2.convs2.1.bias':     'dec.layers.0.resblocks.2.convs2.1.bias',
'dec.resblocks.2.convs2.1.weight_g': 'dec.layers.0.resblocks.2.convs2.1.weight_g',
'dec.resblocks.2.convs2.1.weight_v': 'dec.layers.0.resblocks.2.convs2.1.weight_v',
'dec.resblocks.2.convs2.2.bias':     'dec.layers.0.resblocks.2.convs2.2.bias',
'dec.resblocks.2.convs2.2.weight_g': 'dec.layers.0.resblocks.2.convs2.2.weight_g',
'dec.resblocks.2.convs2.2.weight_v': 'dec.layers.0.resblocks.2.convs2.2.weight_v',

'dec.resblocks.3.convs1.0.bias':     'dec.layers.1.resblocks.0.convs1.0.bias',
'dec.resblocks.3.convs1.0.weight_g': 'dec.layers.1.resblocks.0.convs1.0.weight_g',
'dec.resblocks.3.convs1.0.weight_v': 'dec.layers.1.resblocks.0.convs1.0.weight_v',
'dec.resblocks.3.convs1.1.bias':     'dec.layers.1.resblocks.0.convs1.1.bias',
'dec.resblocks.3.convs1.1.weight_g': 'dec.layers.1.resblocks.0.convs1.1.weight_g',
'dec.resblocks.3.convs1.1.weight_v': 'dec.layers.1.resblocks.0.convs1.1.weight_v',
'dec.resblocks.3.convs1.2.bias':     'dec.layers.1.resblocks.0.convs1.2.bias',
'dec.resblocks.3.convs1.2.weight_g': 'dec.layers.1.resblocks.0.convs1.2.weight_g',
'dec.resblocks.3.convs1.2.weight_v': 'dec.layers.1.resblocks.0.convs1.2.weight_v',
'dec.resblocks.3.convs2.0.bias':     'dec.layers.1.resblocks.0.convs2.0.bias',
'dec.resblocks.3.convs2.0.weight_g': 'dec.layers.1.resblocks.0.convs2.0.weight_g',
'dec.resblocks.3.convs2.0.weight_v': 'dec.layers.1.resblocks.0.convs2.0.weight_v',
'dec.resblocks.3.convs2.1.bias':     'dec.layers.1.resblocks.0.convs2.1.bias',
'dec.resblocks.3.convs2.1.weight_g': 'dec.layers.1.resblocks.0.convs2.1.weight_g',
'dec.resblocks.3.convs2.1.weight_v': 'dec.layers.1.resblocks.0.convs2.1.weight_v',
'dec.resblocks.3.convs2.2.bias':     'dec.layers.1.resblocks.0.convs2.2.bias',
'dec.resblocks.3.convs2.2.weight_g': 'dec.layers.1.resblocks.0.convs2.2.weight_g',
'dec.resblocks.3.convs2.2.weight_v': 'dec.layers.1.resblocks.0.convs2.2.weight_v',

'dec.resblocks.4.convs1.0.bias':     'dec.layers.1.resblocks.1.convs1.0.bias',
'dec.resblocks.4.convs1.0.weight_g': 'dec.layers.1.resblocks.1.convs1.0.weight_g',
'dec.resblocks.4.convs1.0.weight_v': 'dec.layers.1.resblocks.1.convs1.0.weight_v',
'dec.resblocks.4.convs1.1.bias':     'dec.layers.1.resblocks.1.convs1.1.bias',
'dec.resblocks.4.convs1.1.weight_g': 'dec.layers.1.resblocks.1.convs1.1.weight_g',
'dec.resblocks.4.convs1.1.weight_v': 'dec.layers.1.resblocks.1.convs1.1.weight_v',
'dec.resblocks.4.convs1.2.bias':     'dec.layers.1.resblocks.1.convs1.2.bias',
'dec.resblocks.4.convs1.2.weight_g': 'dec.layers.1.resblocks.1.convs1.2.weight_g',
'dec.resblocks.4.convs1.2.weight_v': 'dec.layers.1.resblocks.1.convs1.2.weight_v',
'dec.resblocks.4.convs2.0.bias':     'dec.layers.1.resblocks.1.convs2.0.bias',
'dec.resblocks.4.convs2.0.weight_g': 'dec.layers.1.resblocks.1.convs2.0.weight_g',
'dec.resblocks.4.convs2.0.weight_v': 'dec.layers.1.resblocks.1.convs2.0.weight_v',
'dec.resblocks.4.convs2.1.bias':     'dec.layers.1.resblocks.1.convs2.1.bias',
'dec.resblocks.4.convs2.1.weight_g': 'dec.layers.1.resblocks.1.convs2.1.weight_g',
'dec.resblocks.4.convs2.1.weight_v': 'dec.layers.1.resblocks.1.convs2.1.weight_v',
'dec.resblocks.4.convs2.2.bias':     'dec.layers.1.resblocks.1.convs2.2.bias',
'dec.resblocks.4.convs2.2.weight_g': 'dec.layers.1.resblocks.1.convs2.2.weight_g',
'dec.resblocks.4.convs2.2.weight_v': 'dec.layers.1.resblocks.1.convs2.2.weight_v',

'dec.resblocks.5.convs1.0.bias':     'dec.layers.1.resblocks.2.convs1.0.bias',
'dec.resblocks.5.convs1.0.weight_g': 'dec.layers.1.resblocks.2.convs1.0.weight_g',
'dec.resblocks.5.convs1.0.weight_v': 'dec.layers.1.resblocks.2.convs1.0.weight_v',
'dec.resblocks.5.convs1.1.bias':     'dec.layers.1.resblocks.2.convs1.1.bias',
'dec.resblocks.5.convs1.1.weight_g': 'dec.layers.1.resblocks.2.convs1.1.weight_g',
'dec.resblocks.5.convs1.1.weight_v': 'dec.layers.1.resblocks.2.convs1.1.weight_v',
'dec.resblocks.5.convs1.2.bias':     'dec.layers.1.resblocks.2.convs1.2.bias',
'dec.resblocks.5.convs1.2.weight_g': 'dec.layers.1.resblocks.2.convs1.2.weight_g',
'dec.resblocks.5.convs1.2.weight_v': 'dec.layers.1.resblocks.2.convs1.2.weight_v',
'dec.resblocks.5.convs2.0.bias':     'dec.layers.1.resblocks.2.convs2.0.bias',
'dec.resblocks.5.convs2.0.weight_g': 'dec.layers.1.resblocks.2.convs2.0.weight_g',
'dec.resblocks.5.convs2.0.weight_v': 'dec.layers.1.resblocks.2.convs2.0.weight_v',
'dec.resblocks.5.convs2.1.bias':     'dec.layers.1.resblocks.2.convs2.1.bias',
'dec.resblocks.5.convs2.1.weight_g': 'dec.layers.1.resblocks.2.convs2.1.weight_g',
'dec.resblocks.5.convs2.1.weight_v': 'dec.layers.1.resblocks.2.convs2.1.weight_v',
'dec.resblocks.5.convs2.2.bias':     'dec.layers.1.resblocks.2.convs2.2.bias',
'dec.resblocks.5.convs2.2.weight_g': 'dec.layers.1.resblocks.2.convs2.2.weight_g',
'dec.resblocks.5.convs2.2.weight_v': 'dec.layers.1.resblocks.2.convs2.2.weight_v',

'dec.resblocks.6.convs1.0.bias':     'dec.layers.2.resblocks.0.convs1.0.bias',
'dec.resblocks.6.convs1.0.weight_g': 'dec.layers.2.resblocks.0.convs1.0.weight_g',
'dec.resblocks.6.convs1.0.weight_v': 'dec.layers.2.resblocks.0.convs1.0.weight_v',
'dec.resblocks.6.convs1.1.bias':     'dec.layers.2.resblocks.0.convs1.1.bias',
'dec.resblocks.6.convs1.1.weight_g': 'dec.layers.2.resblocks.0.convs1.1.weight_g',
'dec.resblocks.6.convs1.1.weight_v': 'dec.layers.2.resblocks.0.convs1.1.weight_v',
'dec.resblocks.6.convs1.2.bias':     'dec.layers.2.resblocks.0.convs1.2.bias',
'dec.resblocks.6.convs1.2.weight_g': 'dec.layers.2.resblocks.0.convs1.2.weight_g',
'dec.resblocks.6.convs1.2.weight_v': 'dec.layers.2.resblocks.0.convs1.2.weight_v',
'dec.resblocks.6.convs2.0.bias':     'dec.layers.2.resblocks.0.convs2.0.bias',
'dec.resblocks.6.convs2.0.weight_g': 'dec.layers.2.resblocks.0.convs2.0.weight_g',
'dec.resblocks.6.convs2.0.weight_v': 'dec.layers.2.resblocks.0.convs2.0.weight_v',
'dec.resblocks.6.convs2.1.bias':     'dec.layers.2.resblocks.0.convs2.1.bias',
'dec.resblocks.6.convs2.1.weight_g': 'dec.layers.2.resblocks.0.convs2.1.weight_g',
'dec.resblocks.6.convs2.1.weight_v': 'dec.layers.2.resblocks.0.convs2.1.weight_v',
'dec.resblocks.6.convs2.2.bias':     'dec.layers.2.resblocks.0.convs2.2.bias',
'dec.resblocks.6.convs2.2.weight_g': 'dec.layers.2.resblocks.0.convs2.2.weight_g',
'dec.resblocks.6.convs2.2.weight_v': 'dec.layers.2.resblocks.0.convs2.2.weight_v',

'dec.resblocks.7.convs1.0.bias':     'dec.layers.2.resblocks.1.convs1.0.bias',
'dec.resblocks.7.convs1.0.weight_g': 'dec.layers.2.resblocks.1.convs1.0.weight_g',
'dec.resblocks.7.convs1.0.weight_v': 'dec.layers.2.resblocks.1.convs1.0.weight_v',
'dec.resblocks.7.convs1.1.bias':     'dec.layers.2.resblocks.1.convs1.1.bias',
'dec.resblocks.7.convs1.1.weight_g': 'dec.layers.2.resblocks.1.convs1.1.weight_g',
'dec.resblocks.7.convs1.1.weight_v': 'dec.layers.2.resblocks.1.convs1.1.weight_v',
'dec.resblocks.7.convs1.2.bias':     'dec.layers.2.resblocks.1.convs1.2.bias',
'dec.resblocks.7.convs1.2.weight_g': 'dec.layers.2.resblocks.1.convs1.2.weight_g',
'dec.resblocks.7.convs1.2.weight_v': 'dec.layers.2.resblocks.1.convs1.2.weight_v',
'dec.resblocks.7.convs2.0.bias':     'dec.layers.2.resblocks.1.convs2.0.bias',
'dec.resblocks.7.convs2.0.weight_g': 'dec.layers.2.resblocks.1.convs2.0.weight_g',
'dec.resblocks.7.convs2.0.weight_v': 'dec.layers.2.resblocks.1.convs2.0.weight_v',
'dec.resblocks.7.convs2.1.bias':     'dec.layers.2.resblocks.1.convs2.1.bias',
'dec.resblocks.7.convs2.1.weight_g': 'dec.layers.2.resblocks.1.convs2.1.weight_g',
'dec.resblocks.7.convs2.1.weight_v': 'dec.layers.2.resblocks.1.convs2.1.weight_v',
'dec.resblocks.7.convs2.2.bias':     'dec.layers.2.resblocks.1.convs2.2.bias',
'dec.resblocks.7.convs2.2.weight_g': 'dec.layers.2.resblocks.1.convs2.2.weight_g',
'dec.resblocks.7.convs2.2.weight_v': 'dec.layers.2.resblocks.1.convs2.2.weight_v',

'dec.resblocks.8.convs1.0.bias':     'dec.layers.2.resblocks.2.convs1.0.bias',
'dec.resblocks.8.convs1.0.weight_g': 'dec.layers.2.resblocks.2.convs1.0.weight_g',
'dec.resblocks.8.convs1.0.weight_v': 'dec.layers.2.resblocks.2.convs1.0.weight_v',
'dec.resblocks.8.convs1.1.bias':     'dec.layers.2.resblocks.2.convs1.1.bias',
'dec.resblocks.8.convs1.1.weight_g': 'dec.layers.2.resblocks.2.convs1.1.weight_g',
'dec.resblocks.8.convs1.1.weight_v': 'dec.layers.2.resblocks.2.convs1.1.weight_v',
'dec.resblocks.8.convs1.2.bias':     'dec.layers.2.resblocks.2.convs1.2.bias',
'dec.resblocks.8.convs1.2.weight_g': 'dec.layers.2.resblocks.2.convs1.2.weight_g',
'dec.resblocks.8.convs1.2.weight_v': 'dec.layers.2.resblocks.2.convs1.2.weight_v',
'dec.resblocks.8.convs2.0.bias':     'dec.layers.2.resblocks.2.convs2.0.bias',
'dec.resblocks.8.convs2.0.weight_g': 'dec.layers.2.resblocks.2.convs2.0.weight_g',
'dec.resblocks.8.convs2.0.weight_v': 'dec.layers.2.resblocks.2.convs2.0.weight_v',
'dec.resblocks.8.convs2.1.bias':     'dec.layers.2.resblocks.2.convs2.1.bias',
'dec.resblocks.8.convs2.1.weight_g': 'dec.layers.2.resblocks.2.convs2.1.weight_g',
'dec.resblocks.8.convs2.1.weight_v': 'dec.layers.2.resblocks.2.convs2.1.weight_v',
'dec.resblocks.8.convs2.2.bias':     'dec.layers.2.resblocks.2.convs2.2.bias',
'dec.resblocks.8.convs2.2.weight_g': 'dec.layers.2.resblocks.2.convs2.2.weight_g',
'dec.resblocks.8.convs2.2.weight_v': 'dec.layers.2.resblocks.2.convs2.2.weight_v',

'dec.resblocks.9.convs1.0.bias':     'dec.layers.3.resblocks.0.convs1.0.bias',
'dec.resblocks.9.convs1.0.weight_g': 'dec.layers.3.resblocks.0.convs1.0.weight_g',
'dec.resblocks.9.convs1.0.weight_v': 'dec.layers.3.resblocks.0.convs1.0.weight_v',
'dec.resblocks.9.convs1.1.bias':     'dec.layers.3.resblocks.0.convs1.1.bias',
'dec.resblocks.9.convs1.1.weight_g': 'dec.layers.3.resblocks.0.convs1.1.weight_g',
'dec.resblocks.9.convs1.1.weight_v': 'dec.layers.3.resblocks.0.convs1.1.weight_v',
'dec.resblocks.9.convs1.2.bias':     'dec.layers.3.resblocks.0.convs1.2.bias',
'dec.resblocks.9.convs1.2.weight_g': 'dec.layers.3.resblocks.0.convs1.2.weight_g',
'dec.resblocks.9.convs1.2.weight_v': 'dec.layers.3.resblocks.0.convs1.2.weight_v',
'dec.resblocks.9.convs2.0.bias':     'dec.layers.3.resblocks.0.convs2.0.bias',
'dec.resblocks.9.convs2.0.weight_g': 'dec.layers.3.resblocks.0.convs2.0.weight_g',
'dec.resblocks.9.convs2.0.weight_v': 'dec.layers.3.resblocks.0.convs2.0.weight_v',
'dec.resblocks.9.convs2.1.bias':     'dec.layers.3.resblocks.0.convs2.1.bias',
'dec.resblocks.9.convs2.1.weight_g': 'dec.layers.3.resblocks.0.convs2.1.weight_g',
'dec.resblocks.9.convs2.1.weight_v': 'dec.layers.3.resblocks.0.convs2.1.weight_v',
'dec.resblocks.9.convs2.2.bias':     'dec.layers.3.resblocks.0.convs2.2.bias',
'dec.resblocks.9.convs2.2.weight_g': 'dec.layers.3.resblocks.0.convs2.2.weight_g',
'dec.resblocks.9.convs2.2.weight_v': 'dec.layers.3.resblocks.0.convs2.2.weight_v',

'dec.resblocks.10.convs1.0.bias':     'dec.layers.3.resblocks.1.convs1.0.bias',
'dec.resblocks.10.convs1.0.weight_g': 'dec.layers.3.resblocks.1.convs1.0.weight_g',
'dec.resblocks.10.convs1.0.weight_v': 'dec.layers.3.resblocks.1.convs1.0.weight_v',
'dec.resblocks.10.convs1.1.bias':     'dec.layers.3.resblocks.1.convs1.1.bias',
'dec.resblocks.10.convs1.1.weight_g': 'dec.layers.3.resblocks.1.convs1.1.weight_g',
'dec.resblocks.10.convs1.1.weight_v': 'dec.layers.3.resblocks.1.convs1.1.weight_v',
'dec.resblocks.10.convs1.2.bias':     'dec.layers.3.resblocks.1.convs1.2.bias',
'dec.resblocks.10.convs1.2.weight_g': 'dec.layers.3.resblocks.1.convs1.2.weight_g',
'dec.resblocks.10.convs1.2.weight_v': 'dec.layers.3.resblocks.1.convs1.2.weight_v',
'dec.resblocks.10.convs2.0.bias':     'dec.layers.3.resblocks.1.convs2.0.bias',
'dec.resblocks.10.convs2.0.weight_g': 'dec.layers.3.resblocks.1.convs2.0.weight_g',
'dec.resblocks.10.convs2.0.weight_v': 'dec.layers.3.resblocks.1.convs2.0.weight_v',
'dec.resblocks.10.convs2.1.bias':     'dec.layers.3.resblocks.1.convs2.1.bias',
'dec.resblocks.10.convs2.1.weight_g': 'dec.layers.3.resblocks.1.convs2.1.weight_g',
'dec.resblocks.10.convs2.1.weight_v': 'dec.layers.3.resblocks.1.convs2.1.weight_v',
'dec.resblocks.10.convs2.2.bias':     'dec.layers.3.resblocks.1.convs2.2.bias',
'dec.resblocks.10.convs2.2.weight_g': 'dec.layers.3.resblocks.1.convs2.2.weight_g',
'dec.resblocks.10.convs2.2.weight_v': 'dec.layers.3.resblocks.1.convs2.2.weight_v',

'dec.resblocks.11.convs1.0.bias':     'dec.layers.3.resblocks.2.convs1.0.bias',
'dec.resblocks.11.convs1.0.weight_g': 'dec.layers.3.resblocks.2.convs1.0.weight_g',
'dec.resblocks.11.convs1.0.weight_v': 'dec.layers.3.resblocks.2.convs1.0.weight_v',
'dec.resblocks.11.convs1.1.bias':     'dec.layers.3.resblocks.2.convs1.1.bias',
'dec.resblocks.11.convs1.1.weight_g': 'dec.layers.3.resblocks.2.convs1.1.weight_g',
'dec.resblocks.11.convs1.1.weight_v': 'dec.layers.3.resblocks.2.convs1.1.weight_v',
'dec.resblocks.11.convs1.2.bias':     'dec.layers.3.resblocks.2.convs1.2.bias',
'dec.resblocks.11.convs1.2.weight_g': 'dec.layers.3.resblocks.2.convs1.2.weight_g',
'dec.resblocks.11.convs1.2.weight_v': 'dec.layers.3.resblocks.2.convs1.2.weight_v',
'dec.resblocks.11.convs2.0.bias':     'dec.layers.3.resblocks.2.convs2.0.bias',
'dec.resblocks.11.convs2.0.weight_g': 'dec.layers.3.resblocks.2.convs2.0.weight_g',
'dec.resblocks.11.convs2.0.weight_v': 'dec.layers.3.resblocks.2.convs2.0.weight_v',
'dec.resblocks.11.convs2.1.bias':     'dec.layers.3.resblocks.2.convs2.1.bias',
'dec.resblocks.11.convs2.1.weight_g': 'dec.layers.3.resblocks.2.convs2.1.weight_g',
'dec.resblocks.11.convs2.1.weight_v': 'dec.layers.3.resblocks.2.convs2.1.weight_v',
'dec.resblocks.11.convs2.2.bias':     'dec.layers.3.resblocks.2.convs2.2.bias',
'dec.resblocks.11.convs2.2.weight_g': 'dec.layers.3.resblocks.2.convs2.2.weight_g',
'dec.resblocks.11.convs2.2.weight_v': 'dec.layers.3.resblocks.2.convs2.2.weight_v',
}


for key in weights:
    new_key = key if key not in conversion_weight_labels else conversion_weight_labels[key]
    new_weights.update([(new_key, weights[key])])

# new_weights = weights

model['weight'] = new_weights
model["config"][-3] = model["weight"]["emb_g.weight"].shape[0]

# Test that the import works
from infer.lib.infer_pack.models import SynthesizerTrnMs768NSFsid

net_g = SynthesizerTrnMs768NSFsid(*model["config"], is_half=False)
net_g.load_state_dict(model["weight"], strict=False)

torch.save(model, "assets/weights/charlene_blanchette_modified.pth")


print("hello")  # used for breakpoint